spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pawparazzi?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: dnjswnsdud1.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: "aS3cr3tKeyThatIsLongEnoughToBeSecureAndSafeForHS256"
  expiration: 86400000